services:
  troebel-brewing:
    build:
      context: .
      args:
        - NEXT_PUBLIC_POCKETBASE_URL=https://pb.troebel.wotis-cloud.com
    container_name: troebel-brewing
    restart: unless-stopped
    ports:
      - "8056:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_POCKETBASE_URL=https://pb.troebel.wotis-cloud.com
      - ADMIN_PASSWORD=TroebelAdmin2024
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
